#!/usr/bin/env bash

source /etc/.global-bash-init; _init || exit 1  # needs to be very first for the env vars

restart_copyq() {
    killall copyq && sleep 0.5  # important to sleep; otherwise immediately re-starting copyq it states server's already running.
    silent_background  copyq
}

if pgrep i3 >/dev/null; then
    #sleep 0.5
    i3-msg restart >/dev/null
fi

#sleep 1
# work around https://github.com/hluk/CopyQ/issues/1595
# note: best not do this as-is, as copyq is now likely running as a systemd service.
#if pgrep copyq >/dev/null; then
    #restart_copyq
#fi

exit 0
