#!/usr/bin/env bash

if pgrep i3 >/dev/null; then
    sleep 2
    i3-msg restart
fi

# work around https://github.com/hluk/CopyQ/issues/1595
if pgrep copyq >/dev/null; then
    killall copyq
    sleep 2
    copyq &
fi
