usb_device = "37a8:0003"
# note bctl init _might_ also be executed from autorandr's postswitch script
on_usb_connect_execute = "sh -c \"bctl init; sleep 10; bctl init --retry 2 --sleep 1\""

[monitor1]
monitor_id = "L8LMQS127231"
on_usb_connect = "DisplayPort1"

[monitor2]
monitor_id = "L8LMQS127223"
on_usb_connect = "DisplayPort1"
