#!/usr/bin/env bash

REFRESH_SETTINGS="$HOME/.config/i3/scripts/i3-refresh-settings.sh"

source /etc/.global-bash-init || exit 1  # needs to be very first for the env vars

restart_copyq() {
    systemctl --user restart copyq.service

    # or this if not using systemd service:
    #killall copyq && sleep 0.5  # important to sleep; otherwise immediately re-starting copyq it states server's already running.
    #silent_background  copyq
}

# note bctl init _might_ also be executed from display-switch.ini's on_usb_connect_execute
#pgrep --exact bctld >/dev/null && bctl init --retry 2 --sleep 1
init-monitor.sh -r 2 -s 1

if pgrep --exact i3 >/dev/null; then
    check_progs_installed  "$REFRESH_SETTINGS" i3-apply-rules.sh
    "$REFRESH_SETTINGS"
    i3-msg -q restart
    sleep 0.5 && i3-apply-rules.sh
fi

#sleep 1
# workaround for https://github.com/hluk/CopyQ/issues/1595
#pgrep copyq >/dev/null && restart_copyq

exit 0
